# Generated by Django 2.1 on 2018-08-11 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precondition', models.CharField(default=None, max_length=255, verbose_name='前置条件')),
                ('case_name', models.CharField(default=None, max_length=128, verbose_name='case名称')),
                ('check_step', models.CharField(default=None, max_length=128, verbose_name='检查步骤')),
                ('title', models.CharField(default=None, max_length=64, verbose_name='用例标题')),
                ('step', models.TextField(default=None, max_length=2048, verbose_name='测试步骤')),
                ('phone_name', models.CharField(default=None, max_length=64, verbose_name='机型')),
                ('result', models.ImageField(default=0, upload_to='', verbose_name='测试结果')),
                ('screenshots_path', models.ImageField(default=None, upload_to='upload', verbose_name='测试图片，传入图片路径即可')),
                ('msg', models.TextField(default=None, max_length=1024, verbose_name='失败原因')),
                ('case_id', models.CharField(default=None, max_length=64, verbose_name='case_id')),
                ('report_uuid', models.CharField(default=None, max_length=256, verbose_name='每次运行唯一md5标识')),
                ('report_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform_name', models.TextField(default='android', max_length=16, verbose_name='系统类型')),
                ('case_step_time', models.TextField(default=None, max_length=2048, verbose_name='测试步长，json格式')),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_sum', models.IntegerField(default=0, verbose_name='case总和')),
                ('case_pass_sum', models.IntegerField(default=0, verbose_name='通过case总和')),
                ('case_fail_sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='失败case总和')),
                ('case_skip_sum', models.IntegerField(null=True, verbose_name='跳过case综合')),
                ('case_date', models.DateTimeField(auto_now_add=True, verbose_name='测试日期')),
                ('case_run_time', models.CharField(default='0', max_length=64, verbose_name='测试总耗时')),
                ('platform_name', models.TextField(default='android', max_length=16, verbose_name='系统类型')),
                ('platform_env', models.TextField(default='stage', max_length=16, verbose_name='运行环境')),
                ('report_uuid', models.CharField(default=None, max_length=256, verbose_name='每次运行唯一md5标识')),
                ('report_info_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report_info_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=100)),
                ('aboutme', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
