# Generated by Django 2.1 on 2018-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinfo',
            name='case_fail_sum',
            field=models.IntegerField(default=0, verbose_name='失败case总和'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='case_skip_sum',
            field=models.IntegerField(blank=True, default=0, verbose_name='跳过case综合'),
        ),
    ]
